name: Build

on:
  push:
    branches:
      - 'main'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to Yandex Container Registry
        uses: docker/login-action@v1
        with:
          registry: cr.yandex
          username: ${{ secrets.YA_USER_ID }}
          password: ${{ secrets.YA_PWD }}          
      -
        name: Login to Yandex Cloud Container Registry
        id: login-cr
        uses: yc-actions/yc-cr-login@v1
        with:
          yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}
      -
        name: Build, tag, and push image to Yandex Cloud Container Registry
          env:
            CR_REGISTRY: crpd950roq7aogovvejc
            CR_REPOSITORY: catgpt
            IMAGE_TAG: latest
        run: |
          docker build -f ./build/Dockerfile.prod -t cr.yandex/$CR_REGISTRY/$CR_REPOSITORY:$IMAGE_TAG .
          docker push cr.yandex/$CR_REGISTRY/$CR_REPOSITORY:$IMAGE_TAG
