name: Build

on:
  push:
    branches:
      - 'main'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to Yandex Container Registry
        uses: docker/login-action@v1
        with:
          registry: cr.yandex
          username: ${{ secrets.YA_USER_ID }}
          password: ${{ secrets.YA_PWD }}
      - 
        name: 'Build Inventory Image'
        run: |
          docker build -f build/Dockerfile.prod --tag cr.yandex/crpd950roq7aogovvejc/catgpt:latest
          docker push cr.yandex/crpd950roq7aogovvejc/catgpt:latest
